class RetryError(Exception):
    pass


class DisconnectedError(Exception):
    pass
